export const userData =  [
    {
        firstname:"Roxie",
        lastname:"Mack",
        email:"jevi@nibaka.bw",
        password:"cds8bQgyl"
    },
    {
        firstname:"Ora",
        lastname:"Hubbard",
        email:"karav@ikmo.sm",
        password:"uRov4kM"
    },
    {
        firstname:"Alfred",
        lastname:"Wade",
        email:"husala@lof.es",
        password:"AMBu7gGHqSDNaIxWF"
    },
    {
        firstname:"Lester",
        lastname:"Stewart",
        email:"ocifitogi@zohsal.kp",
        password:"hAHBF7V7OTDRIGLh0Ck"
    },
    {
        firstname:"Mina",
        lastname:"Lucas",
        email:"tuzji@zi.ar",
        password:"8yiJHebeno"
    },
    {
        firstname:"Christine",
        lastname:"Hart",
        email:"duni@ubu.gm",
        password:"uy074"
    },
    {
        firstname:"Bryan",
        lastname:"Fitzgerald",
        email:"ovuwezul@webciane.mu",
        password:"lWauhl3iDYkOoG"
    },
]